// Public
export const EMPLOYEES_FAILURE = 'EMPLOYEES_FAILURE';
export const EMPLOYEES_REQUEST = 'EMPLOYEES_REQUEST';
export const SEARCH_EMPLOYEES = 'SEARCH_EMPLOYEES';

// Create
export const EMPLOYEES_CONFLICT = 'EMPLOYEES_CONFLICT';
export const SAVE_EMPLOYEES = 'SAVE_EMPLOYEES';

// Get
export const GET_EMPLOYEES = 'GET_EMPLOYEES';

// Update
export const DISCONTINUE_EMPLOYEE = ' DISCONTINUE_EMPLOYEE';
export const DISCONTINUE_SUBEMPLOYEE = ' DISCONTINUE_EMPLOYEE';
