// Public
export const CANCELLATIONREASONS_FAILURE = 'CANCELLATIONREASONS_FAILURE';
export const CANCELLATIONREASONS_REQUEST = 'CANCELLATIONREASONS_REQUEST';
export const SEARCH_CANCELLATIONREASONS = 'SEARCH_CANCELLATIONREASONS';

// Create
export const CANCELLATIONREASONS_CONFLICT = 'CANCELLATIONREASONS_CONFLICT';
export const SAVE_CANCELLATIONREASONS = 'SAVE_CANCELLATIONREASONS';

// Get
export const GET_CANCELLATIONREASONS = 'GET_CANCELLATIONREASONS';

// Update
export const DISCONTINUE_CANCELLATIONREASON = ' DISCONTINUE_CANCELLATIONREASON';
