// Public
export const SELLTYPES_FAILURE = 'SELLTYPES_FAILURE';
export const SELLTYPES_REQUEST = 'SELLTYPES_REQUEST';
export const SEARCH_SELLTYPES = 'SEARCH_SELLTYPES';

// Create
export const SELLTYPES_CONFLICT = 'SELLTYPES_CONFLICT';
export const SAVE_SELLTYPES = 'SAVE_SELLTYPES';

// Get
export const GET_SELLTYPES = 'GET_SELLTYPES';

// Update
export const DISCONTINUE_SELLTYPE = ' DISCONTINUE_SELLTYPE';
export const DISCONTINUE_SUBSELLTYPE = ' DISCONTINUE_SELLTYPE';
