// USUARIOS MODALS
export const CREATE_PROFILE = 'CREATE_PROFILE';
export const CREATE_DEPARTAMENT = 'CREATE_DEPARTAMENT';
export const CONFIRM_SAVE_DEPARTAMENTS = 'CONFIRM_SAVE_DEPARTAMENTS';

export const CONFIRM_CHANGES = 'CONFIRM_CHANGES';
