// Public
export const DEPARTAMENTS_FAILURE = 'DEPARTAMENTS_FAILURE';
export const DEPARTAMENTS_REQUEST = 'DEPARTAMENTS_REQUEST';
export const SEARCH_DEPARTAMENTS = 'SEARCH_DEPARTAMENTS';

// Create
export const DEPARTAMENTS_CONFLICT = 'DEPARTAMENTS_CONFLICT';
export const SAVE_DEPARTAMENTS = 'SAVE_DEPARTAMENTS';

// Get
export const GET_DEPARTAMENTS = 'GET_DEPARTAMENTS';

// Update
export const DISCONTINUE_DEPARTAMENT = ' DISCONTINUE_DEPARTAMENT';
export const DISCONTINUE_SUBDEPARTAMENT = ' DISCONTINUE_DEPARTAMENT';
