// Public
export const PRODUCTSANDPRICES_FAILURE = 'PRODUCTSANDPRICES_FAILURE';
export const PRODUCTSANDPRICES_REQUEST = 'PRODUCTSANDPRICES_REQUEST';
export const SEARCH_PRODUCTSANDPRICES = 'SEARCH_PRODUCTSANDPRICES';

// Create
export const PRODUCTSANDPRICES_CONFLICT = 'PRODUCTSANDPRICES_CONFLICT';
export const SAVE_PRODUCTSANDPRICES = 'SAVE_PRODUCTSANDPRICES';

// Get
export const GET_PRODUCTSANDPRICES = 'GET_PRODUCTSANDPRICES';

// Update
export const DISCONTINUE_PRODUCTSANDPRICES = ' DISCONTINUE_PRODUCTSANDPRICES';
