// Public
export const CANCELLATIONS_FAILURE = 'CANCELLATIONS_FAILURE';
export const CANCELLATIONS_REQUEST = 'CANCELLATIONS_REQUEST';
export const SEARCH_CANCELLATIONS = 'SEARCH_CANCELLATIONS';

// Create
export const CANCELLATIONS_CONFLICT = 'CANCELLATIONS_CONFLICT';
export const SAVE_CANCELLATIONS = 'SAVE_CANCELLATIONS';

// Get
export const GET_CANCELLATIONS = 'GET_CANCELLATIONS';

// Update
export const DISCONTINUE_CANCELLATION = ' DISCONTINUE_CANCELLATION';
