// Public
export const PROFILES_FAILURE = 'PROFILES_FAILURE';
export const PROFILES_REQUEST = 'PROFILES_REQUEST';
export const SEARCH_PROFILES = 'SEARCH_PROFILES';

// Create
export const PROFILES_CONFLICT = 'PROFILES_CONFLICT';
export const SAVE_PROFILES = 'SAVE_PROFILES';

// Get
export const GET_PROFILES = 'GET_PROFILES';

// Update
export const DISCONTINUE_PROFILE = ' DISCONTINUE_PROFILE';
export const DISCONTINUE_SUBPROFILE = ' DISCONTINUE_PROFILE';
