// Public
export const DISCOUNTS_FAILURE = 'DISCOUNTS_FAILURE';
export const DISCOUNTS_REQUEST = 'DISCOUNTS_REQUEST';
export const SEARCH_DISCOUNTS = 'SEARCH_DISCOUNTS';

// Create
export const DISCOUNTS_CONFLICT = 'DISCOUNTS_CONFLICT';
export const SAVE_DISCOUNTS = 'SAVE_DISCOUNTS';

// Get
export const GET_DISCOUNTS = 'GET_DISCOUNTS';

// Update
export const DISCONTINUE_DISCOUNT = ' DISCONTINUE_DISCOUNT';
