// Public
export const CATEGORIES_FAILURE = 'CATEGORIES_FAILURE';
export const CATEGORIES_REQUEST = 'CATEGORIES_REQUEST';
export const SEARCH_CATEGORIES = 'SEARCH_CATEGORIES';

// Create
export const CATEGORIES_CONFLICT = 'CATEGORIES_CONFLICT';
export const SAVE_CATEGORIES = 'SAVE_CATEGORIES';

// Get
export const GET_CATEGORIES = 'GET_CATEGORIES';

// Update
export const DISCONTINUE_CATEGORY = ' DISCONTINUE_CATEGORY';
export const DISCONTINUE_SUBCATEGORY = ' DISCONTINUE_CATEGORY';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
