// Public
export const MODIFIERS_FAILURE = 'MODIFIERS_FAILURE';
export const MODIFIERS_REQUEST = 'MODIFIERS_REQUEST';
export const SEARCH_MODIFIERS = 'SEARCH_MODIFIERS';
export const NOT_FOUND_MODIFIERS = 'NOT_FOUND_MODIFIERS';

// Create
export const MODIFIERS_CONFLICT = 'MODIFIERS_CONFLICT';
export const SAVE_MODIFIERS = 'SAVE_MODIFIERS';

// Get
export const GET_MODIFIERS = 'GET_MODIFIERS';

// Delete
export const DELETE_MODIFIERS = 'DELETE_MODIFIERS ';
